{% set name = "git-filter-repo" %}
{% set version = "2.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 4eb8d0774f06ce56995507f1cd59d3f684d13cd09db2fe6fe12766b47d69aedb
    patches:
      - entry-points.patch
  - url: https://github.com/newren/git-filter-repo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz  # [not win]
    sha256: 7bcf11da134bbd82a4171f7fb28a3ab7bc4d478fe8ec3a3d9580e4bbdc32e6e9  # [not win]
    fn: {{ name }}-github-{{ version }}.tar.xz  # [not win]
    folder: orig  # [not win]

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - git >=2.26.0
    - python >=3.5

test:
  requires:
    - pip
  imports:
    - git_filter_repo
  commands:
    - pip check
    - git-filter-repo --version
    - git filter-repo --version

about:
  home: https://github.com/newren/git-filter-repo
  summary: Quickly rewrite git repository history
  dev_url: https://github.com/newren/git-filter-repo
  license: MIT
  license_file: orig/COPYING.mit

extra:
  recipe-maintainers:
    - duncanmmacleod
