{% set name = "git-filter-repo" %}
{% set version = "2.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: fe1753e18f0bd6d3c9b57868c8011ae7d056a6ebab706706396a15ef5312725e
    patches:
      - entry-points.patch
  - url: https://github.com/newren/git-filter-repo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
    sha256: db954f4cae9e47c6be3bd3161bc80540d44f5379cb9cf9df498f4e019f0a41a9
    fn: {{ name }}-github-{{ version }}.tar.xz
    folder: orig

build:
  entry_points:
    - git-filter-repo = git_filter_repo:main
  noarch: python
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - git >=2.26.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    # check entry point
    - git-filter-repo --version
    # check git integration
    - git filter-repo --version

about:
  home: https://github.com/newren/git-filter-repo
  summary: Quickly rewrite git repository history
  dev_url: https://github.com/newren/git-filter-repo
  license: MIT
  license_file: orig/COPYING.mit

extra:
  recipe-maintainers:
    - duncanmmacleod
