{% set name = "git-filter-repo" %}
{% set version = "2.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: b5a09f383865de0a164b06ba174461e55d9167cc6fbb06cf2a1e62dbf0cdba63
    patches:
      - entry-points.patch
  - url: https://github.com/newren/git-filter-repo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
    sha256: b1bf46af1e6a91a54056d0254e480803db8e40f631336c559a1a94d2a08389c4
    fn: {{ name }}-github-{{ version }}.tar.xz
    folder: orig

build:
  entry_points:
    - git-filter-repo = git_filter_repo:main
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - setuptools_scm
  run:
    - git >=2.26.0
    - python >=3.5

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # check entry point
    - git-filter-repo --version
    # check git integration
    - git filter-repo --version

about:
  home: https://github.com/newren/git-filter-repo
  summary: Quickly rewrite git repository history
  dev_url: https://github.com/newren/git-filter-repo
  license: MIT
  license_file: orig/COPYING.mit

extra:
  recipe-maintainers:
    - duncanmmacleod
